[package]
name = "sdpa-sys"
version = "7.3.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

links = "spda_sys"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.61.0"
cc = "1.0.73"
cmake = "0.1.48"
